In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
data_preprocessed = pd.read_csv("C:/Users/Zero/Downloads/Absenteeism_preprocessed.csv")

In [3]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4        Date  \
0           0         0         0         1  2015-07-07   
1           0         0         0         0  2015-07-14   
2           0         0         0         1  2015-07-15   
3           1         0         0         0  2015-07-16   
4           0         0         0         1  2015-07-23   
..        ...       ...       ...       ...         ...   
695         1         0         0         0  2018-05-23   
696         1         0         0         0  2018-05-23   
697         1         0         0         0  2018-05-24   
698         0         0         0         1  2018-05-24   
699         0         0         0         1  2018-05-31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Month Value  Day of the Week  
0              7                1  
1              7                1  
2              7                2  
3              7                3  
4              7                3  
..           ...              ...  
695            5                2  
696            5                2  
697            5                3  
698            5                3  
699            5                3  

[700 rows x 16 columns]

In [4]:
data_preprocessed.describe()

Reason_1    Reason_2    Reason_3    Reason_4  Transportation Expense  \
count  700.000000  700.000000  700.000000  700.000000              700.000000   
mean     0.250000    0.008571    0.090000    0.597143              222.347143   
std      0.433322    0.092250    0.286386    0.490823               66.312960   
min      0.000000    0.000000    0.000000    0.000000              118.000000   
25%      0.000000    0.000000    0.000000    0.000000              179.000000   
50%      0.000000    0.000000    0.000000    1.000000              225.000000   
75%      0.250000    0.000000    0.000000    1.000000              260.000000   
max      1.000000    1.000000    1.000000    1.000000              388.000000   

       Distance to Work         Age  Daily Work Load Average  Body Mass Index  \
count        700.000000  700.000000               700.000000       700.000000   
mean          29.892857   36.417143               271.801774        26.737143   
std           14.804446    6.379083                40.021804         4.254701   
min            5.000000   27.000000               205.917000        19.000000   
25%           16.000000   31.000000               241.476000        24.000000   
50%           26.000000   37.000000               264.249000        25.000000   
75%           50.000000   40.000000               294.217000        31.000000   
max           52.000000   58.000000               378.884000        38.000000   

        Education    Children        Pets  Absenteeism Time in Hours  \
count  700.000000  700.000000  700.000000                 700.000000   
mean     0.167143    1.021429    0.687143                   6.761429   
std      0.373370    1.112215    1.166095                  12.670082   
min      0.000000    0.000000    0.000000                   0.000000   
25%      0.000000    0.000000    0.000000                   2.000000   
50%      0.000000    1.000000    0.000000                   3.000000   
75%      0.000000    2.000000    1.000000                   8.000000   
max      1.000000    4.000000    8.000000                 120.000000   

       Month Value  Day of the Week  
count    700.00000       700.000000  
mean       6.36000         2.011429  
std        3.50501         1.480396  
min        1.00000         0.000000  
25%        3.00000         1.000000  
50%        6.00000         2.000000  
75%       10.00000         3.000000  
max       12.00000         6.000000

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = data_preprocessed['Absenteeism Time in Hours'].apply(lambda x: 1 if x > data_preprocessed['Absenteeism Time in Hours'].median() else 0)

In [7]:
targets

0      1
1      0
2      0
3      1
4      0
      ..
695    1
696    0
697    1
698    0
699    0
Name: Absenteeism Time in Hours, Length: 700, dtype: int64

In [8]:
data_preprocessed['Excessive Absenteeism'] = targets

In [9]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [10]:
targets.value_counts()

Absenteeism Time in Hours
0    381
1    319
Name: count, dtype: int64

In [127]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Daily Work Load Average',
 'Day of the Week',
 'Distance to Work'], axis=1)

In [129]:
data_with_targets is data_preprocessed

False

In [131]:
unscaled_inputs = data_with_targets.drop(['Date'], axis=1).iloc[:,:-1]

In [133]:
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0         0         0         0         1                     289   33   
1         0         0         0         0                     118   50   
2         0         0         0         1                     179   38   
3         1         0         0         0                     279   39   
4         0         0         0         1                     289   33   

   Body Mass Index  Education  Children  Pets  Month Value  
0               30          0         2     1            7  
1               31          0         1     0            7  
2               31          0         0     0            7  
3               24          0         2     0            7  
4               30          0         2     1            7

In [135]:
unscaled_inputs_without_dummies = unscaled_inputs.drop(columns=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education'], axis=1)
dummies = unscaled_inputs[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']]
unscaled_inputs_without_dummies

Transportation Expense  Age  Body Mass Index  Children  Pets  Month Value
0                       289   33               30         2     1            7
1                       118   50               31         1     0            7
2                       179   38               31         0     0            7
3                       279   39               24         2     0            7
4                       289   33               30         2     1            7
..                      ...  ...              ...       ...   ...          ...
695                     179   40               22         2     0            5
696                     225   28               24         1     2            5
697                     330   28               25         0     0            5
698                     235   32               25         0     0            5
699                     291   40               25         1     1            5

[700 rows x 6 columns]

In [137]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [138]:
absenteeism_scaler.fit(unscaled_inputs_without_dummies)

StandardScaler()

In [139]:
scaled_inputs_without_dummies = absenteeism_scaler.transform(unscaled_inputs_without_dummies)

In [140]:
scaled_inputs_without_dummies

array([[ 1.00584437, -0.53606239,  0.76743118,  0.88046927,  0.26848661,
         0.18272635],
       [-1.57468098,  2.13080317,  1.00263338, -0.01928035, -0.58968976,
         0.18272635],
       [-0.6541427 ,  0.24830984,  1.00263338, -0.91902997, -0.58968976,
         0.18272635],
       ...,
       [ 1.62456682, -1.32043461, -0.40857982, -0.91902997, -0.58968976,
        -0.3882935 ],
       [ 0.19094163, -0.69293683, -0.40857982, -0.91902997, -0.58968976,
        -0.3882935 ],
       [ 1.03602595,  0.56205873, -0.40857982, -0.01928035,  0.26848661,
        -0.3882935 ]])

In [141]:
scaled_inputs = pd.DataFrame(scaled_inputs_without_dummies, columns = unscaled_inputs_without_dummies.columns)

In [142]:
scaled_inputs

Transportation Expense       Age  Body Mass Index  Children      Pets  \
0                  1.005844 -0.536062         0.767431  0.880469  0.268487   
1                 -1.574681  2.130803         1.002633 -0.019280 -0.589690   
2                 -0.654143  0.248310         1.002633 -0.919030 -0.589690   
3                  0.854936  0.405184        -0.643782  0.880469 -0.589690   
4                  1.005844 -0.536062         0.767431  0.880469  0.268487   
..                      ...       ...              ...       ...       ...   
695               -0.654143  0.562059        -1.114186  0.880469 -0.589690   
696                0.040034 -1.320435        -0.643782 -0.019280  1.126663   
697                1.624567 -1.320435        -0.408580 -0.919030 -0.589690   
698                0.190942 -0.692937        -0.408580 -0.919030 -0.589690   
699                1.036026  0.562059        -0.408580 -0.019280  0.268487   

     Month Value  
0       0.182726  
1       0.182726  
2       0.182726  
3       0.182726  
4       0.182726  
..           ...  
695    -0.388293  
696    -0.388293  
697    -0.388293  
698    -0.388293  
699    -0.388293  

[700 rows x 6 columns]

In [143]:
scaled_inputs = pd.concat([scaled_inputs, dummies], axis=1)

In [144]:
scaled_inputs

Transportation Expense       Age  Body Mass Index  Children      Pets  \
0                  1.005844 -0.536062         0.767431  0.880469  0.268487   
1                 -1.574681  2.130803         1.002633 -0.019280 -0.589690   
2                 -0.654143  0.248310         1.002633 -0.919030 -0.589690   
3                  0.854936  0.405184        -0.643782  0.880469 -0.589690   
4                  1.005844 -0.536062         0.767431  0.880469  0.268487   
..                      ...       ...              ...       ...       ...   
695               -0.654143  0.562059        -1.114186  0.880469 -0.589690   
696                0.040034 -1.320435        -0.643782 -0.019280  1.126663   
697                1.624567 -1.320435        -0.408580 -0.919030 -0.589690   
698                0.190942 -0.692937        -0.408580 -0.919030 -0.589690   
699                1.036026  0.562059        -0.408580 -0.019280  0.268487   

     Month Value  Reason_1  Reason_2  Reason_3  Reason_4  Education  
0       0.182726         0         0         0         1          0  
1       0.182726         0         0         0         0          0  
2       0.182726         0         0         0         1          0  
3       0.182726         1         0         0         0          0  
4       0.182726         0         0         0         1          0  
..           ...       ...       ...       ...       ...        ...  
695    -0.388293         1         0         0         0          1  
696    -0.388293         1         0         0         0          0  
697    -0.388293         1         0         0         0          1  
698    -0.388293         0         0         0         1          1  
699    -0.388293         0         0         0         1          0  

[700 rows x 11 columns]

In [145]:
from sklearn.model_selection import train_test_split

In [146]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [147]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [148]:
reg = LogisticRegression()

In [149]:
reg.fit(x_train, y_train)

LogisticRegression()

In [150]:
reg.score(x_train, y_train)

0.7732142857142857

In [151]:
model_outputs = reg.predict(x_train)

In [152]:
(model_outputs == y_train).sum()/x_train.shape[0]

0.7732142857142857

In [153]:
x_train.shape[0]

560

In [154]:
reg.intercept_

array([-1.6469898])

In [155]:
reg.coef_

array([[ 0.60513709, -0.16990589,  0.27998236,  0.34842434, -0.27721907,
         0.15897713,  2.80000644,  0.95174778,  3.1140605 ,  0.83835931,
        -0.21017416]])

In [156]:
scaled_inputs.columns

Index(['Transportation Expense', 'Age', 'Body Mass Index', 'Children', 'Pets',
       'Month Value', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Education'],
      dtype='object')

In [157]:
feature_name = scaled_inputs.columns

In [158]:
summary_table = pd.DataFrame(columns=['Feature Names'], data=feature_name)

In [159]:
summary_table

Feature Names
0   Transportation Expense
1                      Age
2          Body Mass Index
3                 Children
4                     Pets
5              Month Value
6                 Reason_1
7                 Reason_2
8                 Reason_3
9                 Reason_4
10               Education

In [160]:
summary_table['Coefficients'] = reg.coef_[0]

In [161]:
summary_table

Feature Names  Coefficients
0   Transportation Expense      0.605137
1                      Age     -0.169906
2          Body Mass Index      0.279982
3                 Children      0.348424
4                     Pets     -0.277219
5              Month Value      0.158977
6                 Reason_1      2.800006
7                 Reason_2      0.951748
8                 Reason_3      3.114061
9                 Reason_4      0.838359
10               Education     -0.210174

In [162]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Names  Coefficients
0                Intercept     -1.646990
1   Transportation Expense      0.605137
2                      Age     -0.169906
3          Body Mass Index      0.279982
4                 Children      0.348424
5                     Pets     -0.277219
6              Month Value      0.158977
7                 Reason_1      2.800006
8                 Reason_2      0.951748
9                 Reason_3      3.114061
10                Reason_4      0.838359
11               Education     -0.210174

In [163]:
summary_table['Odds Ratio'] = np.exp(summary_table['Coefficients'])

In [164]:
summary_table.sort_values(by=['Odds Ratio'], ascending=False)

Feature Names  Coefficients  Odds Ratio
9                 Reason_3      3.114061   22.512270
7                 Reason_1      2.800006   16.444753
8                 Reason_2      0.951748    2.590233
10                Reason_4      0.838359    2.312570
1   Transportation Expense      0.605137    1.831503
4                 Children      0.348424    1.416833
3          Body Mass Index      0.279982    1.323106
6              Month Value      0.158977    1.172311
2                      Age     -0.169906    0.843744
11               Education     -0.210174    0.810443
5                     Pets     -0.277219    0.757888
0                Intercept     -1.646990    0.192629

In [199]:
data_preprocessed['Children'].value_counts()

Children
0    285
1    213
2    146
4     42
3     14
Name: count, dtype: int64

In [166]:
np.sqrt(np.var(data_preprocessed['Children']))

1.111420308452578

In [167]:
sorted(summary_table['Feature Names'].values)

['Age',
 'Body Mass Index',
 'Children',
 'Education',
 'Intercept',
 'Month Value',
 'Pets',
 'Reason_1',
 'Reason_2',
 'Reason_3',
 'Reason_4',
 'Transportation Expense']

In [201]:
reg.score(x_test, y_test)

0.75

In [207]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba[:,1]

array([0.28657484, 0.4126784 , 0.55983847, 0.21836939, 0.91592072,
       0.6651774 , 0.70028794, 0.86887615, 0.21372092, 0.25093422,
       0.50604445, 0.77507998, 0.92864473, 0.26826646, 0.69042146,
       0.45273578, 0.44948079, 0.46073621, 0.59802851, 0.94634518,
       0.29969613, 0.21836939, 0.57971754, 0.57971754, 0.75198536,
       0.25432194, 0.48973443, 0.1430691 , 0.79634796, 0.21836939,
       0.36947677, 0.67913195, 0.68508325, 0.52870791, 0.21836939,
       0.53505228, 0.22144744, 0.73673169, 0.40500758, 0.60504297,
       0.21072119, 0.45227108, 0.23749326, 0.39847178, 0.82763577,
       0.56771922, 0.69120847, 0.28657484, 0.2192347 , 0.2032712 ,
       0.57634482, 0.32954238, 0.6651774 , 0.26937528, 0.83323682,
       0.43484145, 0.88365871, 0.23125087, 0.33433749, 0.34451397,
       0.69915101, 0.6549938 , 0.29244583, 0.79186052, 0.20752232,
       0.26838009, 0.08710411, 0.22144744, 0.73215219, 0.30536526,
       0.22144744, 0.2900789 , 0.90443841, 0.46065771, 0.60175

In [209]:
import pickle

In [217]:
with open('model_12', 'wb') as file:
    pickle.dump(reg, file)

In [219]:
with open('scaler_12', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)